import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Homeschool Hive Knowledge Base Sidebar Configuration
 *
 * The sidebar is auto-generated from the docs folder structure.
 * Category ordering and labels are controlled by _category_.json files.
 *
 * Structure:
 * - intro.md (Getting Started overview)
 * - getting-started/ (Account setup guides)
 * - parents/ (Guides for parents/members)
 * - group-leaders/ (Guides for group administrators)
 * - account/ (Account and settings management)
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
